### ISSUE TITLE
vmap rnamap error : pysam/calignmentfile.pyx single-end

### ISSUE THREAD

**Issue by fcg-bio** [schelhorn/virana#1]
I am trying to run 'vmap rnamap' with the example that you provide in your README.md

``` bash
$vsim reads -r 9626953:5 -r 13095578:5 -r 29502191:50 -r 336087897:50 --read_length=200 -o viral_reads
$vref fasta -r Homo_sapiens -r Viruses -o my_genome_db.fa
$vmap rnaindex -r my_genome_db.fa -i my_rna_index_dir
$vmap rnamap --index my_rna_index_dir --zipped \
  --reads=viral_reads_1.fq.gz --reads=viral_reads_2.fq.gz \
  --virana_hits=hits.bz2
```

This works fine, but when I run it for single end. I got the following error:

``` bash
vmap rnamap --index_dir my_rna_index_dir \
>   --reads=viral_reads_1.fq.gz \
>   --zipped \
>   --star_path='STAR' \
>   --samtools_path='samtools' \
>   --taxonomy=taxonomy.txt \
>   --bam=mapping.bam \
>   --threads=8 \
>   --sensitive \
>   --virana_hits=hits.bz2 \
>   --virana_hit_filter=Viruses \
>   --sample_id=sample_1 \
>   --min_continiously_matching=25 \
>   --max_relative_mismatches=0.2 \
>   -d
Running mapper
Running mapper command line: STAR --runMode alignReads --genomeDir my_rna_index_dir --runThreadN 8 --readMatesLengthsIn NotEqual --outFileNamePrefix /tmp/tmpy1CLeE/out --outSAMmode Full --outSAMstrandField None --outSAMattributes Standard --outSAMunmapped Within --outStd SAM --outFilterMultimapNmax 1000 --outSAMprimaryFlag OneBestScore --limitOutSAMoneReadBytes 1000000 --limitOutSJcollapsed 2000000 --genomeLoad NoSharedMemory --outReadsUnmapped None --readFilesCommand zcat --outFilterMultimapScoreRange 10 --outFilterMismatchNmax 60 --outFilterMismatchNoverLmax 0.3 --outFilterScoreMin 0 --outFilterScoreMinOverLread 0.3 --outFilterMatchNmin 0 --outFilterMatchNminOverLread 0.66 --seedSearchStartLmax 12 --winAnchorMultimapNmax 50 --readFilesIn viral_reads_1.fq.gz
Preparing fifo
Opening fifo for writing
Opened fifo /tmp/tmpy1CLeE/namedpipe
Starting mapper process...
Executed mapper with: STAR --runMode alignReads --genomeDir my_rna_index_dir --runThreadN 8 --readMatesLengthsIn NotEqual --outFileNamePrefix /tmp/tmpy1CLeE/out --outSAMmode Full --outSAMstrandField None --outSAMattributes Standard --outSAMunmapped Within --outStd SAM --outFilterMultimapNmax 1000 --outSAMprimaryFlag OneBestScore --limitOutSAMoneReadBytes 1000000 --limitOutSJcollapsed 2000000 --genomeLoad NoSharedMemory --outReadsUnmapped None --readFilesCommand zcat --outFilterMultimapScoreRange 10 --outFilterMismatchNmax 60 --outFilterMismatchNoverLmax 0.3 --outFilterScoreMin 0 --outFilterScoreMinOverLread 0.3 --outFilterMatchNmin 0 --outFilterMatchNminOverLread 0.66 --seedSearchStartLmax 12 --winAnchorMultimapNmax 50 --readFilesIn viral_reads_1.fq.gz
Setting outputs
Opening input SAM parser and fifo
Parsing mapper output from pysam fifo /tmp/tmpy1CLeE/namedpipe
Extracting header from pysam fifo...
Finished extracting header of length 4
Outputting taxonomy to taxonomy.txt
Outputting virana hits to hits.bz2
Outputting BAM file to mapping.bam
Starting to parse with pysam...
Parsing SAM file alignments...
Processed 0 SAM alignments
Traceback (most recent call last):
  File "/home/fcastro/bin/vmap", line 5, in <module>
    virana.vmap.CLI.run()
  File "/usr/local/lib/python2.7/dist-packages/plumbum/cli/application.py", line 352, in run
    inst, retcode = subapp.run(argv, exit = False)
  File "/usr/local/lib/python2.7/dist-packages/plumbum/cli/application.py", line 348, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/lib/python2.7/dist-packages/Virana-1.1.0-py2.7.egg/virana/vmap.py", line 1347, in main
    for alignment, parsed_line in parser.parse():
  File "/usr/local/lib/python2.7/dist-packages/Virana-1.1.0-py2.7.egg/virana/vmap.py", line 346, in parse
    mate_ref_name       = getrname(alignment.rnext)
  File "pysam/calignmentfile.pyx", line 570, in pysam.calignmentfile.AlignmentFile.getrname (pysam/calignmentfile.c:7987)
ValueError: reference_id -1 out of range 0<=tid<1974

```

I am using latest virana version, STAR 2.4.0j , samtools 1.2, pysam 0.8.2

It is an issue generated by the last updates of pysam or I am doing something wrong?

Thanks

**Comment by paretini** [comment]
Hi,
I had the same problem by running  single end reads from Ion Proton. Did you solve a this time this issue?
Thanks
Paolo

**Comment by fcg-bio** [comment]
No, still on stand by...

Francesc

**Comment by paretini** [comment]
Did you write to the author?

**Comment by fcg-bio** [comment]
no, but I will at some point.

**Comment by paretini** [comment]
Okay. I think that I'll write now.

Paolo Aretini PhD
Senior Bioinformatics Analyst
Fondazione Pisana per la Scienza ONLUS
Via Panfilo Castaldi, 2
56121, Pisa (PI) Italy
Tel +39050974061; Fax: +390509656178;
E:mail: p.aretini@fondazionepisascienza.org

Da:"Francesc Castro" notifications@github.com
Data:Gio, 16 Apr, 2015 alle 14:38
Oggetto:Re: [virana] vmap rnamap error : pysam/calignmentfile.pyx single-end (#1)

no, but I will at some point.
